app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
_imagine:
    resource: .
    type: imagine
    
_backend_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    resource: .
    type: extra